using Backend.Data;
using Backend.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Data.Common;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

const string FrontendCorsPolicy = "FrontendCorsPolicy";

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddCors(options =>
{
    options.AddPolicy(FrontendCorsPolicy, policy =>
    {
        policy
            .SetIsOriginAllowed(origin =>
            {
                if (!Uri.TryCreate(origin, UriKind.Absolute, out var parsedOrigin))
                {
                    return false;
                }

                return string.Equals(parsedOrigin.Host, "localhost", StringComparison.OrdinalIgnoreCase)
                    || string.Equals(parsedOrigin.Host, "127.0.0.1", StringComparison.OrdinalIgnoreCase);
            })
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

builder.Services.AddScoped<EmailService>();
builder.Services.AddScoped<IJwtTokenService, JwtTokenService>();

var resolvedConnectionString =
    builder.Configuration.GetConnectionString("DefaultConnection") ??
    "Data Source=garagego-local.db";

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseSqlite(resolvedConnectionString));

var jwtKey = builder.Configuration["Jwt:Key"] ?? "garagego_super_secret_key_123456789";
var jwtIssuer = builder.Configuration["Jwt:Issuer"];
var jwtAudience = builder.Configuration["Jwt:Audience"];

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = !string.IsNullOrWhiteSpace(jwtIssuer),
            ValidateAudience = !string.IsNullOrWhiteSpace(jwtAudience),
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = jwtIssuer,
            ValidAudience = jwtAudience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey))
        };
    });

var app = builder.Build();

try
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

    await db.Database.EnsureCreatedAsync();
    await EnsureOperationalSchemaAsync(db);
}
catch (Exception ex)
{
    var logger = app.Services.GetRequiredService<ILogger<Program>>();
    logger.LogError(ex, "An error occurred while preparing the database schema.");
}

app.UseSwagger();
app.UseSwaggerUI();
app.UseHttpsRedirection();
app.UseCors(FrontendCorsPolicy);
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();

static async Task EnsureOperationalSchemaAsync(AppDbContext db)
{
    var connection = db.Database.GetDbConnection();
    var providerName = db.Database.ProviderName ?? string.Empty;

    if (connection.State != System.Data.ConnectionState.Open)
    {
        await connection.OpenAsync();
    }

    var existingTables = await GetTableNamesAsync(connection, providerName);

    await EnsureTableAsync(
        db,
        existingTables,
        "Staff",
        """
        CREATE TABLE IF NOT EXISTS "Staff" (
            "Id" INTEGER NOT NULL CONSTRAINT "PK_Staff" PRIMARY KEY AUTOINCREMENT,
            "Name" TEXT NOT NULL,
            "Email" TEXT NOT NULL,
            "Password" TEXT NOT NULL,
            "Role" TEXT NOT NULL
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "Staff" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" character varying(120) NOT NULL,
            "Email" character varying(200) NOT NULL,
            "Password" character varying(255) NOT NULL,
            "Role" character varying(30) NOT NULL
        );
        """);

    await EnsureSqlAsync(db, "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Staff_Email\" ON \"Staff\" (\"Email\");");

    await EnsureTableAsync(
        db,
        existingTables,
        "Vendors",
        """
        CREATE TABLE IF NOT EXISTS "Vendors" (
            "Id" INTEGER NOT NULL CONSTRAINT "PK_Vendors" PRIMARY KEY AUTOINCREMENT,
            "VendorName" TEXT NOT NULL,
            "CompanyName" TEXT NOT NULL,
            "Phone" TEXT NOT NULL,
            "Email" TEXT NOT NULL,
            "Address" TEXT NOT NULL,
            "CreatedAt" TEXT NOT NULL
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "Vendors" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VendorName" text NOT NULL,
            "CompanyName" text NOT NULL,
            "Phone" text NOT NULL,
            "Email" text NOT NULL,
            "Address" text NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        );
        """);

    await EnsureTableAsync(
        db,
        existingTables,
        "Parts",
        """
        CREATE TABLE IF NOT EXISTS "Parts" (
            "Id" INTEGER NOT NULL CONSTRAINT "PK_Parts" PRIMARY KEY AUTOINCREMENT,
            "PartName" TEXT NOT NULL,
            "Category" TEXT NOT NULL,
            "Price" numeric(18,2) NOT NULL,
            "Quantity" INTEGER NOT NULL,
            "Description" TEXT NOT NULL,
            "VendorId" INTEGER NOT NULL,
            "CreatedAt" TEXT NOT NULL,
            CONSTRAINT "FK_Parts_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "Parts" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PartName" text NOT NULL,
            "Category" text NOT NULL,
            "Price" numeric(18,2) NOT NULL,
            "Quantity" integer NOT NULL,
            "Description" text NOT NULL,
            "VendorId" integer NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_Parts_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT
        );
        """);

    await EnsureSqlAsync(db, "CREATE INDEX IF NOT EXISTS \"IX_Parts_VendorId\" ON \"Parts\" (\"VendorId\");");

    await EnsureTableAsync(
        db,
        existingTables,
        "Sales",
        """
        CREATE TABLE IF NOT EXISTS "Sales" (
            "Id" INTEGER NOT NULL CONSTRAINT "PK_Sales" PRIMARY KEY AUTOINCREMENT,
            "CustomerId" INTEGER NOT NULL,
            "Date" TEXT NOT NULL,
            "TotalAmount" numeric(18,2) NOT NULL
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "Sales" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CustomerId" integer NOT NULL,
            "Date" timestamp with time zone NOT NULL,
            "TotalAmount" numeric(18,2) NOT NULL
        );
        """);

    await EnsureTableAsync(
        db,
        existingTables,
        "SaleItems",
        """
        CREATE TABLE IF NOT EXISTS "SaleItems" (
            "Id" INTEGER NOT NULL CONSTRAINT "PK_SaleItems" PRIMARY KEY AUTOINCREMENT,
            "PartId" INTEGER NOT NULL,
            "Quantity" INTEGER NOT NULL,
            "Price" numeric(18,2) NOT NULL,
            "SaleId" INTEGER NOT NULL,
            CONSTRAINT "FK_SaleItems_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "SaleItems" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PartId" integer NOT NULL,
            "Quantity" integer NOT NULL,
            "Price" numeric(18,2) NOT NULL,
            "SaleId" integer NOT NULL,
            CONSTRAINT "FK_SaleItems_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE
        );
        """);

    await EnsureSqlAsync(db, "CREATE INDEX IF NOT EXISTS \"IX_SaleItems_SaleId\" ON \"SaleItems\" (\"SaleId\");");

    var existingColumns = await GetTableColumnsAsync(connection, providerName, "ServiceHistories");

    if (existingColumns.Count == 0)
    {
        return;
    }

    if (existingColumns.Contains("Cost") && !existingColumns.Contains("Amount"))
    {
        await EnsureSqlAsync(db, "ALTER TABLE \"ServiceHistories\" RENAME COLUMN \"Cost\" TO \"Amount\";");
        existingColumns.Remove("Cost");
        existingColumns.Add("Amount");
    }

    if (existingColumns.Contains("ServiceType") && !existingColumns.Contains("HistoryType"))
    {
        await EnsureSqlAsync(db, "ALTER TABLE \"ServiceHistories\" RENAME COLUMN \"ServiceType\" TO \"HistoryType\";");
        existingColumns.Remove("ServiceType");
        existingColumns.Add("HistoryType");
    }

    if (!existingColumns.Contains("Title"))
    {
        await EnsureSqlAsync(db, "ALTER TABLE \"ServiceHistories\" ADD COLUMN \"Title\" TEXT NOT NULL DEFAULT '';");
        existingColumns.Add("Title");
    }

    if (!existingColumns.Contains("PaymentStatus"))
    {
        await EnsureSqlAsync(db, "ALTER TABLE \"ServiceHistories\" ADD COLUMN \"PaymentStatus\" TEXT NOT NULL DEFAULT 'Paid';");
        existingColumns.Add("PaymentStatus");
    }

    if (!existingColumns.Contains("InvoiceNumber"))
    {
        await EnsureSqlAsync(db, "ALTER TABLE \"ServiceHistories\" ADD COLUMN \"InvoiceNumber\" TEXT NULL;");
        existingColumns.Add("InvoiceNumber");
    }

    if (existingColumns.Contains("HistoryType") && existingColumns.Contains("Title"))
    {
        await EnsureSqlAsync(
            db,
            """
            UPDATE "ServiceHistories"
            SET "Title" = CASE
                WHEN COALESCE(TRIM("Title"), '') = '' THEN COALESCE("HistoryType", 'History')
                ELSE "Title"
            END,
                "PaymentStatus" = COALESCE(NULLIF(TRIM("PaymentStatus"), ''), 'Paid');
            """);
    }
}

static async Task<HashSet<string>> GetTableNamesAsync(DbConnection connection, string providerName)
{
    var tables = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

    await using var command = connection.CreateCommand();
    command.CommandText = providerName.Contains("Npgsql", StringComparison.OrdinalIgnoreCase)
        ? "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';"
        : "SELECT name FROM sqlite_master WHERE type = 'table';";

    await using var reader = await command.ExecuteReaderAsync();
    while (await reader.ReadAsync())
    {
        tables.Add(reader.GetString(0));
    }

    return tables;
}

static async Task<HashSet<string>> GetTableColumnsAsync(DbConnection connection, string providerName, string tableName)
{
    var columns = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

    await using var command = connection.CreateCommand();

    if (providerName.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
    {
        command.CommandText = "SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = @tableName;";
        var parameter = command.CreateParameter();
        parameter.ParameterName = "@tableName";
        parameter.Value = tableName;
        command.Parameters.Add(parameter);
    }
    else
    {
        command.CommandText = $"PRAGMA table_info('{tableName.Replace("'", "''")}');";
    }

    await using var reader = await command.ExecuteReaderAsync();
    while (await reader.ReadAsync())
    {
        columns.Add(providerName.Contains("Npgsql", StringComparison.OrdinalIgnoreCase)
            ? reader.GetString(0)
            : reader.GetString(1));
    }

    return columns;
}

static async Task EnsureTableAsync(
    AppDbContext db,
    HashSet<string> existingTables,
    string tableName,
    string sqliteSql,
    string postgresSql)
{
    if (existingTables.Contains(tableName))
    {
        return;
    }

    await EnsureSqlAsync(db, sqliteSql);

    existingTables.Add(tableName);
}

static async Task EnsureSqlAsync(AppDbContext db, string sql)
{
    await db.Database.ExecuteSqlRawAsync(sql);
}
